[package]
name = "d2s-rs"
version = "0.1.0"
authors = ["Paul Linchpiner <paul@linchpiner.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
failure = "0.1.5"
num = "0.4.0"
num-traits = "0.2"
num-derive = "0.3"